CUDA_visible_GPUs:
    - "0"

list_of_primitives:
    - 'sphere'
    - 'plane'
    - 'cylinder'
    - 'cone'

is_nn: true

n_max_instances: 24
batch_size: 16

prediction_dir: "results/val_pred/stepXXXXX"
test_data_file: "traceparts_data/test_models.csv"
test_first_n: -1
test_data_noisy: true
bundle_dir: "results/val_bundle_final"
